install:
	# $ sudo apt install tesseract-ocr -y
	# $ pip install pytesseract
	# $ pip install random_user_agent
	# $ pip install opencv-python
	# $ pip install random_user_agent
	# $ pip install pyqt5
